# Generated by Django 5.2 on 2025-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HappinessRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("rank", models.PositiveIntegerField()),
                ("country_name", models.CharField(max_length=255)),
                ("ladder_score", models.FloatField()),
                ("upperwhisker", models.FloatField()),
                ("lowerwhisker", models.FloatField()),
                ("log_gdp_per_capita", models.FloatField()),
                ("social_support", models.FloatField()),
                ("healthy_life_expectancy", models.FloatField()),
                ("freedom_to_make_life_choices", models.FloatField()),
                ("generosity", models.FloatField()),
                ("perceptions_of_corruption", models.FloatField()),
                ("dystopia_residual", models.FloatField()),
            ],
        ),
    ]
