# Generated by Django 5.2 on 2025-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellbeing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="happinessrecord",
            name="dystopia_residual",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="freedom_to_make_life_choices",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="generosity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="healthy_life_expectancy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="ladder_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="log_gdp_per_capita",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="lowerwhisker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="perceptions_of_corruption",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="social_support",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happinessrecord",
            name="upperwhisker",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
