# Generated by Django 5.2 on 2025-04-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MusicTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("artists", models.CharField(blank=True, max_length=255, null=True)),
                ("daily_rank", models.IntegerField(blank=True, null=True)),
                ("daily_movement", models.IntegerField(blank=True, null=True)),
                ("weekly_movement", models.IntegerField(blank=True, null=True)),
                ("snapshot_date", models.DateField()),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("is_explicit", models.BooleanField(default=False)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("album_name", models.CharField(blank=True, max_length=255, null=True)),
                ("album_release_date", models.DateField(blank=True, null=True)),
                ("danceability", models.FloatField(blank=True, null=True)),
                ("energy", models.FloatField(blank=True, null=True)),
                ("key", models.IntegerField(blank=True, null=True)),
                ("loudness", models.FloatField(blank=True, null=True)),
                ("mode", models.IntegerField(blank=True, null=True)),
                ("speechiness", models.FloatField(blank=True, null=True)),
                ("acousticness", models.FloatField(blank=True, null=True)),
                ("instrumentalness", models.FloatField(blank=True, null=True)),
                ("liveness", models.FloatField(blank=True, null=True)),
                ("valence", models.FloatField(blank=True, null=True)),
                ("tempo", models.FloatField(blank=True, null=True)),
                ("time_signature", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="music.country",
                    ),
                ),
            ],
        ),
    ]
