# Generated by Django 5.2 on 2025-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bienetre", "0002_alter_happinessrecord_dystopia_residual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentalHealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measure_id", models.IntegerField(blank=True, null=True)),
                (
                    "measure_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location_id", models.IntegerField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sex_id", models.IntegerField(blank=True, null=True)),
                ("sex_name", models.CharField(blank=True, max_length=255, null=True)),
                ("age_id", models.IntegerField(blank=True, null=True)),
                ("age_name", models.CharField(blank=True, max_length=255, null=True)),
                ("cause_id", models.IntegerField(blank=True, null=True)),
                ("cause_name", models.CharField(blank=True, max_length=255, null=True)),
                ("metric_id", models.IntegerField(blank=True, null=True)),
                (
                    "metric_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("val", models.FloatField(blank=True, null=True)),
                ("upper", models.FloatField(blank=True, null=True)),
                ("lower", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
