# Generated by Django 5.2 on 2025-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MergedDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=10)),
                ("ladder_score", models.FloatField(blank=True, null=True)),
                ("upperwhisker", models.FloatField(blank=True, null=True)),
                ("lowerwhisker", models.FloatField(blank=True, null=True)),
                ("log_gdp_per_capita", models.FloatField(blank=True, null=True)),
                ("social_support", models.FloatField(blank=True, null=True)),
                ("healthy_life_expectancy", models.FloatField(blank=True, null=True)),
                (
                    "freedom_to_make_life_choices",
                    models.FloatField(blank=True, null=True),
                ),
                ("perceptions_of_corruption", models.FloatField(blank=True, null=True)),
                ("dystopia_residual", models.FloatField(blank=True, null=True)),
                ("danceability", models.FloatField(blank=True, null=True)),
                ("energy", models.FloatField(blank=True, null=True)),
                ("loudness", models.FloatField(blank=True, null=True)),
                ("acousticness", models.FloatField(blank=True, null=True)),
                ("instrumentalness", models.FloatField(blank=True, null=True)),
                ("valence", models.FloatField(blank=True, null=True)),
                ("tempo", models.FloatField(blank=True, null=True)),
                ("anxiety_disorders", models.FloatField(blank=True, null=True)),
                ("bipolar_disorder", models.FloatField(blank=True, null=True)),
                ("depressive_disorders", models.FloatField(blank=True, null=True)),
                ("mental_disorders", models.FloatField(blank=True, null=True)),
                ("other_mental_disorders", models.FloatField(blank=True, null=True)),
                ("schizophrenia", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
